language: python
python:
- '2.7'
- '3.3'
- '3.4'
- pypy
- pypy3
install:
- pip install .[tests] sphinx
script:
- nosetests tests -v --processes=4
- sphinx-build -W docs /dev/shm/sphinx
env:
  global:
    secure: sgamcAoKAiuSSKvkIECtXeT04DGjLkaaxr44j1Bp1CMg6xk3Xv/JVLGOdDKublT/nEvBWfbTzO9BT+YchfHcY44DPwCcFQfTb79N9SMst7/OUaYrank05+XDJF4L19s461TSMkWnjNLSBhQ2vkasRgxhcYilPm4V93Ux4qss9UdvXHIs/a2lmS7oSeHKrASNPerACAfMV5CMvngk/9+hYZAnPztai+GaoJvQAwBAloUcZ1WfvFyXZh9WWa4hQXcUD0zkKCCvqYuSEHRfF8EyKtP/DrnPJUkDabH8CK4HlF+JlSdSy1ymsaAGEsRiIemRZuAMoSaNE3sFSvKPCOdkKQLPGQaKIS5Nj9piB/JY427vCsAdsAm6kY1mrVneOMxp8BjoCOQ3jRVV7itVL17z+FD+XtK/P2B++Ebb8doMNnmKVLNq+4dcaaa4Q4BFF6a1/nukCfIAW0dzCJ2ap/GlIFbP8+zl83xDa0kPeTgR1RFOp5exGoqMiGlj2PSFqAXFUb2Aje3Iim9zH5ThOqvFNhMdEs/gDEslaaYwfzp4TR958eItQW+WXU62pe1SAOvnm//bkxQHI6l8tpiVAkeZh9Rn+asgDiBIPV95SytOvcvipJEcyDBhqcT8FNb3q/1GWm5xSU4IKhQKM00UaHbmcblb2Kb5aRYsmuHl5DcRIj4=
password:
  secure: CFr2COcy01kgAJWp8+148+VN9ekI7bp6zJ1jwUsB3DSOqbtqwbROT2K+pzzPEQhMF3JigCwbV3p6RZQdakRxHipQS0AAB/tyzHlB0yrkC8KUvY+EPcWUj/v//ONjEtSHHwKJNWq8lXUUU9ETMPmZcdE7copdfB7MagBZS427YsAq5OZe/JerTpSmVG5aFSI02R5AiO2S9zw+SNBi3g5wBfsgcchUxTOAqVqU+Qh4p/tDzA4XSun1RNjPK/UHepRbZ0v2i6mGIQj1LTnszm2eiQML7PWXsMixGffqqcWoDBpVa72yY1lx9VTgqUe40e8d3Vzpa55K00dQwxK0JK1HaOyB8CRxXWckgZFxXT2bZjnPGfAOjUTWnWXROdWmzDsfup1jzet4GPpKedoODjlTHG1NDfP8ibE49dLx9M5ieQVL8MA16pKNCuzq7uqRN9o3L8NGE8cDupQFcH93+ztQhL8PJ+cgrhqeJAUrbGefBe9tOI1ZBMD7NfublNu6EJjgVxYB5THMPa3QS2ov9dQyxbQ2za17/SfRitRFM1yFF6upf2xNboPjRTTrOtwNTpZO9dGurT86inl4+iS+//e7K2RnRtuwVXFX2IyTQu/pzMbcpi4dId1fDMLeUxuDLuD2fI+WSREzn+hYQ73D9wnxHYxKoRTy08ji4HiEQVKgpHE=
